language: java
jdk: openjdk13

git:
    submodules: false

jobs:
    include:
    - stage: build
      install: skip
      script: "./gradlew clean build"

    - stage: publish-release
      if: tag =~ ^v
      install: skip
      script: "./gradlew bintrayUpload"

    - stage: report-coverage
      if: branch = master
      install: skip
      script: "./gradlew test jacocoTestReport jacocoRootReport coveralls"

env:
    global:
        # BINTRAY_USER
        - secure: RUIFOrP/Keumsup/yRLlR44Rdz9SNGeIcN3OtO6RDvlpR9pHzdHida1cZA+CCf7WtwFZfOo6YuMdlEcN48bFAd9GHEh1AaNL61Yut/ANO4BjixdouyMaj52mWOG+KgaGEB9W3tXx02gbzTrhLfaLC7U5gsCDrhEbbGHgs07jIQEmC7iAtAKmSLzWW9j9tpwpLpLttDGg5UNpuHuKw7lx+A/pH4o3ilPhZXcWKKcUNTjLPWNam0XZ4uy6QgJvEsN7exMWE0r434+hfS4aXwf5nTptN90id7cETxEFjGLUlbPSXVOXePUoImWmMZNhy3uM2xpy8NPEaDdcyayMuUxzrRiBVVhogHVzypIyoeczdReG0DaRlWk+HySrfvWmluDOl6xAOy1QkDs1gwoaC8rcr8dqM6v1kT7uYhk5r4LPXw/qZaeMevpQg8uL3+isNdp09/sCeUzwqIwNzWKqSbO7AD14RyVf3az4eW7JPV5W2OpfTUAhQrzlevCC7omS6ia8GH23gAWr8FpCwYO7FrUU1EQzKFn7DTjPtY1uQuSMEd7KqIO9R0yJqS63SdTh1hfrhLbIy4bRuoG4p1aefamcY6PdIqGFMkgjgzOLL5l5CVJSCQa+hwwQulkxEyTu5FyM22eXZ4R+LAXW9Om1v+U7sdlRCAs6o3V6bs5bdLhKOX4=
        # BINTRAY_API_KEY
        - secure: OhEbBTKLh0q1R1GywbMblBs+OoDUvJYZgbiw0/eun2RGRmF5POlrunTItkVm7gPPeYzMd1weQHn9tzhmI6MrirEsj04EpVa4kvtREjqnqH6h5lNYVrJzRD0zWZNOJ7BJDHSQm8kZ9RsVDyAS1biI0bnyvARf0+1mrxKD0duAPJJK6GRFQAKR4DYRModEKbz1ufWNQBGgLPinwEoEzwu0FgP1RoqLub65CmxOWqsguezAI6I1NYRzDFGpXwR2Iwb8zGw9nhyN8SyTOzlWTXQ2V0JqpQQYaUEbAqDam1Li67gLZf5xXOTMkFOAjJhx5hYCad/90gtag1meDpNJqZa8jH9MxNS5TDs2A+Q3gfNF1SkevlHokeJdGUypUXhUXG617Fi6f4ph/2g3pJML0GqnDKQ7WtCmzpnRfqx269N4utX7FEaRCr7VfcS0LorqLzN/YXETak5CuVI33ObRbvzDXqLreHUjfWQuB3PF54fRA3gVFc7hXRCfdYTReVcQPlgmAVDNWuD0uNNDL6g92glndR9J3X8rERrnU+4HjAo2VvQ2drWPLroDTZjXQDLYW2jKVkQgolCd2c4Se4N/+HCuGTFgRihAK3OCkjGE8RDbWy6PnAkgiwfTdJI7bTKLEOcpOY7WKeQY9/1y1xuPFD7K3TgS2sZAMHZQQwuCr1x8tDs=
