name: CI

on: [push, pull_request]

jobs:
    build:
        runs-on: ubuntu-latest
        env:
            jdk_version: 13
            SONATYPE_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
            SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
            SIGNING_KEY: ${{ secrets.SIGNING_KEY }}
            COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
        steps:
            - name: Checkout
              uses: actions/checkout@v2

            - name: Setup JDK ${{ env.jdk_version }}
              uses: actions/setup-java@v1
              with:
                  java-version: ${{ env.jdk_version }}

            - name: Build
              run: ./gradlew clean build

            - name: Cross-version tests
              run: |
                  sudo apt-get update
                  sudo apt-get install zsh
                  ./run-tests.zsh

            - name: Publish release
              if: startsWith(github.ref, 'refs/tags/v')
              run: ./gradlew publish

            - name: Report coverage
              if: github.ref == 'refs/heads/master'
              run: ./gradlew test jacocoTestReport jacocoRootReport coveralls
